/**
 * Created by renhui on 2014/8/22.
 */
exports.secondaryClasss=[
    {"secondaryClassID": 1,"secondaryName":"运动服饰",   "oneLevelID": 1},
    {"secondaryClassID": 2,"secondaryName":"时尚新品",   "oneLevelID": 1},
    {"secondaryClassID": 3,"secondaryName":"文具玩具",   "oneLevelID": 1},
    {"secondaryClassID": 4,"secondaryName":"钟表",       "oneLevelID": 1},
    {"secondaryClassID": 5,"secondaryName":"其他",       "oneLevelID": 1},
    {"secondaryClassID": 6,"secondaryName":"家乐福",     "oneLevelID": 2},
    {"secondaryClassID": 7,"secondaryName":"沃尔玛",     "oneLevelID": 2},
    {"secondaryClassID": 8,"secondaryName":"永辉",       "oneLevelID": 2},
    {"secondaryClassID": 9,"secondaryName":"京客隆",     "oneLevelID": 2},
    {"secondaryClassID":10,"secondaryName":"物美",       "oneLevelID": 2},
    {"secondaryClassID":11,"secondaryName":"亿客隆",     "oneLevelID": 2},
    {"secondaryClassID":12,"secondaryName":"华普",       "oneLevelID": 2},
    {"secondaryClassID":13,"secondaryName":"世纪联华",   "oneLevelID": 2},
    {"secondaryClassID":14,"secondaryName":"顺天府",     "oneLevelID": 2},
    {"secondaryClassID":15,"secondaryName":"欧尚",       "oneLevelID": 2},
    {"secondaryClassID":16,"secondaryName":"万客隆",     "oneLevelID": 2},
    {"secondaryClassID":17,"secondaryName":"超市发",     "oneLevelID": 2},
    {"secondaryClassID":18,"secondaryName":"易初莲花",   "oneLevelID": 2},
    {"secondaryClassID":19,"secondaryName":"其他",       "oneLevelID": 2},
    {"secondaryClassID":20,"secondaryName":"川菜",       "oneLevelID": 3},
    {"secondaryClassID":21,"secondaryName":"粤菜",       "oneLevelID": 3},
    {"secondaryClassID":22,"secondaryName":"火锅",       "oneLevelID": 3},
    {"secondaryClassID":23,"secondaryName":"自助",       "oneLevelID": 3},
    {"secondaryClassID":24,"secondaryName":"烧烤",       "oneLevelID": 3},
    {"secondaryClassID":25,"secondaryName":"海鲜",       "oneLevelID": 3},
    {"secondaryClassID":26,"secondaryName":"家常菜",     "oneLevelID": 3},
    {"secondaryClassID":27,"secondaryName":"粥店",       "oneLevelID": 3},
    {"secondaryClassID":28,"secondaryName":"小吃",       "oneLevelID": 3},
    {"secondaryClassID":29,"secondaryName":"其他",       "oneLevelID": 3},
    {"secondaryClassID":30,"secondaryName":"美容",       "oneLevelID": 4},
    {"secondaryClassID":31,"secondaryName":"美发",       "oneLevelID": 4},
    {"secondaryClassID":32,"secondaryName":"摄影",       "oneLevelID": 4},
    {"secondaryClassID":33,"secondaryName":"洗衣",       "oneLevelID": 4},
    {"secondaryClassID":34,"secondaryName":"其他",       "oneLevelID": 4},
    {"secondaryClassID":35,"secondaryName":"数码\\通讯", "oneLevelID": 5},
    {"secondaryClassID":36,"secondaryName":"图书音像",   "oneLevelID": 5},
    {"secondaryClassID":37,"secondaryName":"数码周边",   "oneLevelID": 5},
    {"secondaryClassID":38,"secondaryName":"其他",       "oneLevelID": 5},
    {"secondaryClassID":39,"secondaryName":"足疗保健",   "oneLevelID": 6},
    {"secondaryClassID":40,"secondaryName":"电影院",     "oneLevelID": 6},
    {"secondaryClassID":41,"secondaryName":"KTV",        "oneLevelID": 6},
    {"secondaryClassID":42,"secondaryName":"剧场",       "oneLevelID": 6},
    {"secondaryClassID":43,"secondaryName":"其他",       "oneLevelID": 6},
    {"secondaryClassID":44,"secondaryName":"特色塑身",   "oneLevelID": 7},
    {"secondaryClassID":45,"secondaryName":"健身场馆",   "oneLevelID": 7},
    {"secondaryClassID":46,"secondaryName":"户外健身",   "oneLevelID": 7},
    {"secondaryClassID":47,"secondaryName":"其他",       "oneLevelID": 7},
    {"secondaryClassID":48,"secondaryName":"味多美",     "oneLevelID": 8},
    {"secondaryClassID":49,"secondaryName":"好利来",     "oneLevelID": 8},
    {"secondaryClassID":50,"secondaryName":"黑天鹅",     "oneLevelID": 8},
    {"secondaryClassID":51,"secondaryName":"面包新语",   "oneLevelID": 8},
    {"secondaryClassID":52,"secondaryName":"金凤呈祥",   "oneLevelID": 8},
    {"secondaryClassID":53,"secondaryName":"其他",       "oneLevelID": 8},
    {"secondaryClassID":54,"secondaryName":"车辆清洁",   "oneLevelID": 9},
    {"secondaryClassID":55,"secondaryName":"加油站",     "oneLevelID": 9},
    {"secondaryClassID":56,"secondaryName":"维修服务",   "oneLevelID": 9},
    {"secondaryClassID":57,"secondaryName":"其他",       "oneLevelID": 9},
    {"secondaryClassID":58,"secondaryName":"家具家居",   "oneLevelID":10},
    {"secondaryClassID":59,"secondaryName":"装修服务",   "oneLevelID":10},
    {"secondaryClassID":60,"secondaryName":"其他",       "oneLevelID":10},
    {"secondaryClassID":61,"secondaryName":"网上商城",   "oneLevelID":11},
    {"secondaryClassID":62,"secondaryName":"医疗",       "oneLevelID":12},
    {"secondaryClassID":63,"secondaryName":"体检",       "oneLevelID":12},
    {"secondaryClassID":64,"secondaryName":"其他",       "oneLevelID":12},
    {"secondaryClassID":65,"secondaryName":"旅游服务",   "oneLevelID":13},
    {"secondaryClassID":66,"secondaryName":"其他",       "oneLevelID":13},
    {"secondaryClassID":67,"secondaryName":"贵重金属",   "oneLevelID":14},
    {"secondaryClassID":68,"secondaryName":"瓷器\\玉器", "oneLevelID":14},
    {"secondaryClassID":69,"secondaryName":"其他",       "oneLevelID":14}
];