exports.area = [
    {"areaID":  1, "areaName":"东城区",  "cityID":1},
    {"areaID":  2, "areaName":"西城区",  "cityID":1},
    {"areaID":  5, "areaName":"朝阳区",  "cityID":1},
    {"areaID":  6, "areaName":"丰台区",  "cityID":1},
    {"areaID":  7, "areaName":"石景山区","cityID":1},
    {"areaID":  8, "areaName":"海淀区",  "cityID":1},
    {"areaID":  9, "areaName":"门头沟区","cityID":1},
    {"areaID": 10, "areaName":"房山区",  "cityID":1},
    {"areaID": 11, "areaName":"通州区",  "cityID":1},
    {"areaID": 12, "areaName":"顺义区",  "cityID":1},
    {"areaID": 13, "areaName":"昌平区",  "cityID":1},
    {"areaID": 14, "areaName":"大兴区",  "cityID":1},
    {"areaID": 15, "areaName":"怀柔区",  "cityID":1},
    {"areaID": 16, "areaName":"平谷区",  "cityID":1},
    {"areaID": 17, "areaName":"密云县",  "cityID":1},
    {"areaID": 18, "areaName":"延庆县",  "cityID":1},
    {"areaID": 37, "areaName":"黄浦区",  "cityID":3},
    {"areaID": 38, "areaName":"卢湾区",  "cityID":3},
    {"areaID": 39, "areaName":"徐汇区",  "cityID":3},
    {"areaID": 40, "areaName":"长宁区",  "cityID":3},
    {"areaID": 41, "areaName":"静安区",  "cityID":3},
    {"areaID": 42, "areaName":"普陀区",  "cityID":3},
    {"areaID": 43, "areaName":"闸北区",  "cityID":3},
    {"areaID": 44, "areaName":"虹口区",  "cityID":3},
    {"areaID": 45, "areaName":"杨浦区",  "cityID":3},
    {"areaID": 46, "areaName":"闵行区",  "cityID":3},
    {"areaID": 47, "areaName":"宝山区",  "cityID":3},
    {"areaID": 48, "areaName":"嘉定区",  "cityID":3},
    {"areaID": 49, "areaName":"浦东新区","cityID":3},
    {"areaID": 50, "areaName":"金山区",  "cityID":3},
    {"areaID": 51, "areaName":"松江区",  "cityID":3},
    {"areaID": 52, "areaName":"青浦区",  "cityID":3},
    {"areaID": 53, "areaName":"南汇区",  "cityID":3},
    {"areaID": 54, "areaName":"奉贤区",  "cityID":3},
    {"areaID": 55, "areaName":"崇明县",  "cityID":3},
    {"areaID":268, "areaName":"越秀区",  "cityID":190},
    {"areaID":269, "areaName":"荔湾区",  "cityID":190},
    {"areaID":270, "areaName":"海珠区",  "cityID":190},
    {"areaID":271, "areaName":"天河区",  "cityID":190},
    {"areaID":272, "areaName":"白云区",  "cityID":190},
    {"areaID":273, "areaName":"黄埔区",  "cityID":190},
    {"areaID":274, "areaName":"番禺区",  "cityID":190},
    {"areaID":275, "areaName":"花都区",  "cityID":190},
    {"areaID":276, "areaName":"南沙区",  "cityID":190},
    {"areaID":277, "areaName":"萝岗区",  "cityID":190},
    {"areaID":278, "areaName":"增城市",  "cityID":190},
    {"areaID":279, "areaName":"从化市",  "cityID":190}
];